# HTTP Server
server:
  port: 8080

spring:
  application:
    name: pos-gateway
  # freemarker:
  #   enabled: true # Use Eureka dashboard FreeMarker templates
  cloud:
    gateway:
      routes:
        - id: pos-product
          uri: lb://pos-product
          predicates:
          - Path=/api/products/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - OPTIONS
              allowedHeaders: '*'
              maxAge: 30
        - id: pos-product-setting
          uri: lb://pos-product
          predicates:
            - Path=/api/settings
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - OPTIONS
              allowedHeaders: '*'
              maxAge: 30
        - id: pos-product-categories
          uri: lb://pos-product
          predicates:
            - Path=/api/categories
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - OPTIONS
              allowedHeaders: '*'
              maxAge: 30
        - id: pos-order
          uri: lb://pos-order
          predicates:
          - Path=/api/orders/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - OPTIONS
              allowedHeaders: '*'
              maxAge: 30

# error.path: /error

# Discovery Server Access
#  1. DEV ONLY: Reduce the lease renewal interval to speed up registration
#  2. Define URL of registration server (defaultZone)
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      # leaseRenewalIntervalInSeconds: 10
      hostname: localhost

logging:
  level:
    org.springframework.cloud.gateway: DEBUG